### ISSUE TITLE
Need valid geocode service URL

### ISSUE THREAD

**Issue by pattyjula** [what3words/w3w-arcgis-experience-builder-widget#1]
I am having trouble setting a valid geocode service URL. I followed the steps over [here](https://github.com/what3words/w3w-arcgis-experience-builder-widget/), but I'm not sure why the URL isn't working. I can insert the widget, but I can't see the locator which I had previously set up. I'm right around the bullet point in the README for 

> Then click on your Locator, scroll down to the bottom of the page, on the right-hand 

Can someone help me debug? I have my node server and client running and I think I must be close.
![image](https://user-images.githubusercontent.com/5982211/184041281-cfc9dfe2-b144-443c-bf4e-cf50baeeff93.png)

**Comment by ManuCiao** [comment]
Hi, I am working on fixing this issue. currently, The widget picks up the top locator that has been added to the utility services of your organisation as it is shown in this screenshot, in this example it is the `what3words_EN_English dev`

![image](https://user-images.githubusercontent.com/17753696/184131642-8d8616c1-653d-4a1f-ac6a-c90195a81f89.png)

once you have updated your utility services, reload your experience app to allow the app to pick up the updates.

I update the widget asap. thanks for reporting this issue. I am keen to hear any feedback from you. thanks

**Comment by pattyjula** [comment]
Thanks, that's a big help. I moved the w3w locator to the top of that list and now I can add it.
