### ISSUE TITLE
Compatibility issue with Experience Builder 1.12

### ISSUE THREAD

**Issue by Jeffrey-Thompson** [what3words/w3w-arcgis-experience-builder-widget#2]
I have just upgraded to Experience Builder 1.12 and the what3words widget is showing different information in the map than the widget.  The first click on the map will show null on the map surface with the words appearing in the widget. On any subsequent clicks, the map will be one location behind the widget. I believe this is related to [Automatic Batching](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching) in React 18.

I was able to resolve the issue by passing response directly into the getMapLabelGraphic function rather than doing it through state.

![image](https://github.com/what3words/w3w-arcgis-experience-builder-widget/assets/63476951/9e34dfb1-33ed-4e34-99cb-a4553219e6ad)
![image](https://github.com/what3words/w3w-arcgis-experience-builder-widget/assets/63476951/c203a146-6601-473c-95f8-f69a1092c41d)

**Comment by ManuCiao** [comment]
@Jeffrey-Thompson I will upgrade it and fix the issue. I will let you know when it is done. thanks for reporting this issue.

**Comment by ManuCiao** [comment]
I have upgraded the widget to be compatible with exp builder v1.15 and fixed the issue you reported above. thanks
